import { geoContains } from "d3-geo";
import { feature } from "topojson-client";
import worldTopology from "world-atlas/countries-50m.json" with { type: "json" };
import { writeFileSync } from "fs";

// 50m (Natural Earth 1:50m) resolution — needed so small Aegean islands
// (Crete, the Cyclades, etc.) actually show up instead of being simplified
// away like they were at 110m. (world-atlas's 10m dataset has a malformed
// polygon somewhere that makes d3-geo's geoContains return true for every
// point tested, including mid-ocean — confirmed by direct testing — so 50m
// is the highest resolution that actually works correctly here.)
const land = feature(worldTopology, worldTopology.objects.countries);

// Geographic window: Mediterranean / Europe / Middle East, so İzmir lands
// somewhere legible rather than being one pixel on a whole-world map.
const LON_MIN = 8;
const LON_MAX = 38;
const LAT_MIN = 25;
const LAT_MAX = 65;

const COLS = 54;
const ROWS = 72;
const SUBSAMPLES = 3; // per axis, per cell — avoids missing thin islands

const dots = [];
for (let row = 0; row < ROWS; row++) {
  for (let col = 0; col < COLS; col++) {
    let hit = false;
    for (let sy = 0; sy < SUBSAMPLES && !hit; sy++) {
      for (let sx = 0; sx < SUBSAMPLES && !hit; sx++) {
        const lon = LON_MIN + ((col + (sx + 0.5) / SUBSAMPLES) / COLS) * (LON_MAX - LON_MIN);
        const lat = LAT_MAX - ((row + (sy + 0.5) / SUBSAMPLES) / ROWS) * (LAT_MAX - LAT_MIN);
        if (geoContains(land, [lon, lat])) hit = true;
      }
    }
    if (hit) dots.push([col, row]);
  }
}

const IZMIR = { lon: 27.14, lat: 38.42 };
const izmirCol = ((IZMIR.lon - LON_MIN) / (LON_MAX - LON_MIN)) * COLS;
const izmirRow = ((LAT_MAX - IZMIR.lat) / (LAT_MAX - LAT_MIN)) * ROWS;

const output = `// Generated by scripts/generate-dotmap.mjs — do not hand-edit.
// Land dots sampled from world-atlas (10m) over a Mediterranean/Europe/
// Middle East window (lon ${LON_MIN}..${LON_MAX}, lat ${LAT_MIN}..${LAT_MAX})
// on a ${COLS}x${ROWS} grid (${SUBSAMPLES}x${SUBSAMPLES} subsamples per cell),
// so İzmir's marker lands somewhere legible.

export const DOT_MAP_COLS = ${COLS};
export const DOT_MAP_ROWS = ${ROWS};

export const DOT_MAP_LAND: [number, number][] = ${JSON.stringify(dots)};

export const IZMIR_DOT = { col: ${izmirCol.toFixed(2)}, row: ${izmirRow.toFixed(2)} };
`;

writeFileSync(new URL("../lib/dotmap-data.ts", import.meta.url), output);
console.log(`Wrote ${dots.length} land dots. İzmir at col=${izmirCol.toFixed(2)}, row=${izmirRow.toFixed(2)}`);
